FROM oven/bun AS build

WORKDIR /app

# Cache packages installation
COPY package.json bun.lock tsconfig.json ./

ENV DATABASE_URL=$DATABASE_URL

RUN bun install --production

COPY ./src ./src

ENV NODE_ENV=production

RUN bun build \
	--compile \
	--minify-whitespace \
	--minify-syntax \
	--outfile server \
	src/index.ts

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/server server

ENV NODE_ENV=production

CMD ["./server"]

EXPOSE 3000